In [2]:
import nfl_data_py as nfl                                                                                                                     
import pandas as pd                                                                                                                           
                                                                                                                                            
df = nfl.import_seasonal_data([2023, 2024])                                                                                                   
print(df.shape)                                             
df.head()

(1195, 58)

,player_id,season,season_type,completions,attempts,passing_yards,passing_tds,interceptions,sacks,sack_yards,...,yac_sh,wopr_y,ry_sh,rtd_sh,rfd_sh,rtdfd_sh,dom,w8dom,yptmpa,ppr_sh
0,00-0023459,2023,REG,0,1,0.0,0,0.0,1.0,10.0,...,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,00-0023459,2024,REG,368,584,3897.0,28,11.0,40.0,302.0,...,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.177032
2,00-0024243,2023,REG,0,0,0.0,0,0.0,0.0,0.0,...,0.069712,0.057342,0.027384,0.125,0.036364,0.047619,0.076192,0.046907,0.197279,0.028467
3,00-0024243,2024,REG,0,0,0.0,0,0.0,0.0,0.0,...,0.006757,0.059271,0.008850,0.000,0.071429,0.055556,0.004425,0.007080,0.068966,0.010541
4,00-0026158,2023,REG,123,204,1616.0,13,8.0,8.0,57.0,...,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.191464

In [3]:
df.columns.tolist()

['player_id',
 'season',
 'season_type',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'interceptions',
 'sacks',
 'sack_yards',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_2pt_conversions',
 'pacr',
 'dakota',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'racr',
 'target_share',
 'air_yards_share',
 'wopr_x',
 'special_teams_tds',
 'fantasy_points',
 'fantasy_points_ppr',
 'games',
 'tgt_sh',
 'ay_sh',
 'yac_sh',
 'wopr_y',
 'ry_sh',
 'rtd_sh',
 'rfd_sh',
 'rtdfd_sh',
 'dom',
 'w8dom',
 'yptmpa',
 'ppr_sh']

In [4]:
qbs = df[(df['season'] == 2024) & (df['attempts'] > 100)].copy()
qbs = qbs[['player_id', 'passing_yards', 'passing_tds', 'interceptions', 'attempts']].sort_values('passing_yards', ascending=False)           
qbs.head(10)

      player_id  passing_yards  passing_tds  interceptions  attempts
616  00-0036442         4918.0           43            9.0       652
160  00-0033106         4629.0           37           12.0       539
363  00-0034855         4500.0           41           16.0       570
52   00-0030565         4320.0           21           15.0       578
368  00-0034869         4319.0           35           12.0       545
345  00-0034796         4172.0           41            4.0       474
234  00-0033873         3928.0           26           11.0       581
1    00-0023459         3897.0           28           11.0       584
583  00-0036355         3870.0           23            3.0       504
876  00-0037834         3864.0           20           12.0       455

In [10]:
players = players[['gsis_id', 'display_name', 'position']]                                                                                    
                                                                                                                                                
qbs = qbs.merge(players, left_on='player_id', right_on='gsis_id', how='left')                                                                 
qbs[['display_name', 'position', 'passing_yards', 'passing_tds', 'interceptions', 'attempts']].head(10)

,display_name,position,passing_yards,passing_tds,interceptions,attempts
0,Joe Burrow,QB,4918.0,43,9.0,652
1,Jared Goff,QB,4629.0,37,12.0,539
2,Baker Mayfield,QB,4500.0,41,16.0,570
3,Geno Smith,QB,4320.0,21,15.0,578
4,Sam Darnold,QB,4319.0,35,12.0,545
5,Lamar Jackson,QB,4172.0,41,4.0,474
6,Patrick Mahomes,QB,3928.0,26,11.0,581
7,Aaron Rodgers,QB,3897.0,28,11.0,584
8,Justin Herbert,QB,3870.0,23,3.0,504
9,Brock Purdy,QB,3864.0,20,12.0,455

In [7]:
players.columns.tolist()

['gsis_id',
 'display_name',
 'common_first_name',
 'first_name',
 'last_name',
 'short_name',
 'football_name',
 'suffix',
 'esb_id',
 'nfl_id',
 'pfr_id',
 'pff_id',
 'otc_id',
 'espn_id',
 'smart_id',
 'birth_date',
 'position_group',
 'position',
 'ngs_position_group',
 'ngs_position',
 'height',
 'weight',
 'headshot',
 'college_name',
 'college_conference',
 'jersey_number',
 'rookie_season',
 'last_season',
 'latest_team',
 'status',
 'ngs_status',
 'ngs_status_short_description',
 'years_of_experience',
 'pff_position',
 'pff_status',
 'draft_year',
 'draft_round',
 'draft_pick',
 'draft_team']

In [18]:
rbs = df[(df['season'] == 2024) & (df['carries'] > 50)].copy()
rbs['yards_per_carry'] = rbs['rushing_yards'] / rbs['carries']
rbs = rbs[['player_id', 'carries', 'rushing_yards', 'rushing_tds', 'yards_per_carry']].sort_values('rushing_yards', ascending=False)

players = players[['gsis_id', 'display_name', 'position']]                                                                                    
                                                                                                                                                
rbs = rbs.merge(players, left_on='player_id', right_on='gsis_id', how='left')                                                                 
rbs[['gsis_id', 'display_name', 'position', 'rushing_yards', 'rushing_tds', 'carries', 'yards_per_carry']].head(10)

,gsis_id,display_name,position,rushing_yards,rushing_tds,carries,yards_per_carry
0,00-0034844,Saquon Barkley,RB,2005.0,13,345,5.811594
1,00-0032764,Derrick Henry,RB,1921.0,16,325,5.910769
2,00-0038542,Bijan Robinson,RB,1456.0,14,304,4.789474
3,00-0036223,Jonathan Taylor,RB,1431.0,11,303,4.722772
4,00-0039139,Jahmyr Gibbs,RB,1412.0,16,250,5.648000
5,00-0035700,Josh Jacobs,RB,1329.0,15,301,4.415282
6,00-0037840,Kyren Williams,RB,1299.0,14,316,4.110759
7,00-0036555,Chuba Hubbard,RB,1195.0,10,250,4.780000
8,00-0033293,Aaron Jones,RB,1138.0,5,255,4.462745
9,00-0039361,Bucky Irving,RB,1122.0,8,207,5.420290

In [26]:
rbs23 = df[(df['season'] == 2023) & (df['carries'] > 50)].copy()
rbs23['yards_per_carry'] = rbs23['rushing_yards'] / rbs23['carries']

rbs = df[(df['season'] == 2024) & (df['carries'] > 50)].copy()
rbs['yards_per_carry'] = rbs['rushing_yards'] / rbs['carries']

top_ids = rbs.sort_values('rushing_yards', ascending=False).head(10)['player_id'].tolist()                                
rbsmerge = rbs[rbs['player_id'].isin(top_ids)].merge(rbs23, on='player_id', suffixes=('_2024', '_2023'), how='left')
rbsmerge['ypc_improvement'] = rbsmerge['yards_per_carry_2024'] - rbsmerge['yards_per_carry_2023']

rbsmerge = rbsmerge.merge(players, left_on='player_id', right_on='gsis_id', how='left')                                   
                                                                                                                            
rbsmerge[['display_name', 'rushing_yards_2024', 'rushing_yards_2023', 'yards_per_carry_2024', 'yards_per_carry_2023',     
'ypc_improvement']].sort_values('ypc_improvement', ascending=False).head(10)

,display_name,rushing_yards_2024,rushing_yards_2023,yards_per_carry_2024,yards_per_carry_2023,ypc_improvement
2,Saquon Barkley,2005.0,962.0,5.811594,3.894737,1.916857
0,Derrick Henry,1921.0,1167.0,5.910769,4.167857,1.742912
5,Chuba Hubbard,1195.0,902.0,4.780000,3.789916,0.990084
3,Josh Jacobs,1329.0,805.0,4.415282,3.454936,0.960347
8,Jahmyr Gibbs,1412.0,945.0,5.648000,5.192308,0.455692
4,Jonathan Taylor,1431.0,741.0,4.722772,4.384615,0.338157
7,Bijan Robinson,1456.0,976.0,4.789474,4.560748,0.228726
1,Aaron Jones,1138.0,656.0,4.462745,4.619718,-0.156973
6,Kyren Williams,1299.0,1144.0,4.110759,5.017544,-0.906784
9,Bucky Irving,1122.0,NaN,5.420290,NaN,NaN